FROM microsoft/aspnetcore-build:2.0
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

EXPOSE 80

WORKDIR /src
COPY *.sln ./
COPY ClassLibrary1/ClassLibrary1.csproj ClassLibrary1/
COPY WebApplication120/WebApplication120.csproj WebApplication120/
RUN dotnet restore -nowarn:msb3202,nu1503
COPY . .
WORKDIR /src/WebApplication120
RUN dotnet build WebApplication120.csproj

CMD ["dotnet", "run", "--no-restore", "--no-build", "--no-launch-profile"]
